### PR TITLE
Bump @aws-cdk packages to 1.74.0

### PR DESCRIPTION
**Pull request by Gibzon69**
Just wanted to bump cdk packages to latest. Tests works, port forwarding works.

### CODE REVIEW

**Comment by snowiow** [comment]
Hi, thanks for the contribution 🙂 Could you merge the current master back into your branch? We switched CI over to GitHub Actions, because CircleCI seems to be really unreliable lately.

**Comment by Gibzon69** [comment]
Done! :)

**Comment by snowiow** [comment]
ty!

**Review by snowiow — APPROVED** [review]

**Comment by Gibzon69** [comment]
Np. And thank you for such a helpful construct. It was just what I needed!

**Pull request merged**
